steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/customer-health-score:$COMMIT_SHA', '.']

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-health-score:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'customer-health-score'
    - '--image'
    - 'gcr.io/$PROJECT_ID/customer-health-score:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'
    - '--concurrency'
    - '100'
    - '--timeout'
    - '300'
    - '--set-env-vars'
    - 'NODE_ENV=production,PORT=8080,DB_PATH=/tmp/customer_health.db'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/customer-health-score:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY