# Create cloudbuild.yaml file
echo "steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'src/backend'

  # Build frontend
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'src/frontend'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'customer-health-score'
    - '--source'
    - 'src/backend'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'NODE_ENV=production,PORT=8080,DB_PATH=/tmp/customer_health.db'" > cloudbuild.yaml